// Code generated by protoc-gen-go. DO NOT EDIT.
// source: host.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HostInfoMessageRequest struct {
	Req                  *Request `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostInfoMessageRequest) Reset()         { *m = HostInfoMessageRequest{} }
func (m *HostInfoMessageRequest) String() string { return proto.CompactTextString(m) }
func (*HostInfoMessageRequest) ProtoMessage()    {}
func (*HostInfoMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85e40b83b4d50a8d, []int{0}
}

func (m *HostInfoMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfoMessageRequest.Unmarshal(m, b)
}
func (m *HostInfoMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfoMessageRequest.Marshal(b, m, deterministic)
}
func (m *HostInfoMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfoMessageRequest.Merge(m, src)
}
func (m *HostInfoMessageRequest) XXX_Size() int {
	return xxx_messageInfo_HostInfoMessageRequest.Size(m)
}
func (m *HostInfoMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfoMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfoMessageRequest proto.InternalMessageInfo

func (m *HostInfoMessageRequest) GetReq() *Request {
	if m != nil {
		return m.Req
	}
	return nil
}

type HostInfoMessageResponse struct {
	Host                 *HostInfo `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HostInfoMessageResponse) Reset()         { *m = HostInfoMessageResponse{} }
func (m *HostInfoMessageResponse) String() string { return proto.CompactTextString(m) }
func (*HostInfoMessageResponse) ProtoMessage()    {}
func (*HostInfoMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85e40b83b4d50a8d, []int{1}
}

func (m *HostInfoMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfoMessageResponse.Unmarshal(m, b)
}
func (m *HostInfoMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfoMessageResponse.Marshal(b, m, deterministic)
}
func (m *HostInfoMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfoMessageResponse.Merge(m, src)
}
func (m *HostInfoMessageResponse) XXX_Size() int {
	return xxx_messageInfo_HostInfoMessageResponse.Size(m)
}
func (m *HostInfoMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfoMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfoMessageResponse proto.InternalMessageInfo

func (m *HostInfoMessageResponse) GetHost() *HostInfo {
	if m != nil {
		return m.Host
	}
	return nil
}

type HostInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostInfo) Reset()         { *m = HostInfo{} }
func (m *HostInfo) String() string { return proto.CompactTextString(m) }
func (*HostInfo) ProtoMessage()    {}
func (*HostInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_85e40b83b4d50a8d, []int{2}
}

func (m *HostInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfo.Unmarshal(m, b)
}
func (m *HostInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfo.Marshal(b, m, deterministic)
}
func (m *HostInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfo.Merge(m, src)
}
func (m *HostInfo) XXX_Size() int {
	return xxx_messageInfo_HostInfo.Size(m)
}
func (m *HostInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfo proto.InternalMessageInfo

func (m *HostInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_85e40b83b4d50a8d, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*HostInfoMessageRequest)(nil), "proto.HostInfoMessageRequest")
	proto.RegisterType((*HostInfoMessageResponse)(nil), "proto.HostInfoMessageResponse")
	proto.RegisterType((*HostInfo)(nil), "proto.HostInfo")
	proto.RegisterType((*Request)(nil), "proto.Request")
}

func init() {
	proto.RegisterFile("host.proto", fileDescriptor_85e40b83b4d50a8d)
}

var fileDescriptor_85e40b83b4d50a8d = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0x2f, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x56, 0x5c, 0x62, 0x1e, 0xf9,
	0xc5, 0x25, 0x9e, 0x79, 0x69, 0xf9, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x0a, 0x5c, 0xcc, 0x45, 0xa9, 0x85, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xdc, 0x46, 0x7c, 0x10, 0x5d, 0x7a, 0x50, 0xc9, 0x20, 0x90, 0x94, 0x92, 0x1d, 0x97, 0x38, 0x86,
	0xde, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x65, 0x2e, 0x16, 0x90, 0x5d, 0x50, 0xdd, 0xfc,
	0x50, 0xdd, 0x30, 0xd5, 0x41, 0x60, 0x49, 0x25, 0x15, 0x2e, 0x0e, 0x98, 0x88, 0x90, 0x04, 0x17,
	0x7b, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0x31, 0x58, 0x0f, 0x67, 0x10, 0x8c, 0xab, 0x24, 0xcb,
	0xc5, 0x0e, 0x73, 0x92, 0x10, 0x17, 0x4b, 0x69, 0x69, 0x66, 0x0a, 0x54, 0x05, 0x98, 0x6d, 0x94,
	0xc4, 0xc5, 0xed, 0x5e, 0x94, 0x9a, 0x5a, 0x12, 0x9c, 0x5a, 0x96, 0x99, 0x9c, 0x2a, 0x14, 0xcc,
	0x25, 0xe0, 0x92, 0x0f, 0xb7, 0x07, 0xa2, 0x4d, 0x16, 0xcd, 0x7a, 0x54, 0x8f, 0x4a, 0xc9, 0xe1,
	0x92, 0x86, 0xf8, 0x45, 0x89, 0xc1, 0x89, 0x2d, 0x8a, 0x25, 0x37, 0x31, 0x33, 0x2f, 0x89, 0x0d,
	0xac, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x97, 0xd6, 0x31, 0x48, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreetSeviceClient is the client API for GreetSevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetSeviceClient interface {
	DoHostInfoRquest(ctx context.Context, in *HostInfoMessageRequest, opts ...grpc.CallOption) (*HostInfoMessageResponse, error)
}

type greetSeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetSeviceClient(cc grpc.ClientConnInterface) GreetSeviceClient {
	return &greetSeviceClient{cc}
}

func (c *greetSeviceClient) DoHostInfoRquest(ctx context.Context, in *HostInfoMessageRequest, opts ...grpc.CallOption) (*HostInfoMessageResponse, error) {
	out := new(HostInfoMessageResponse)
	err := c.cc.Invoke(ctx, "/proto.GreetSevice/DoHostInfoRquest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetSeviceServer is the server API for GreetSevice service.
type GreetSeviceServer interface {
	DoHostInfoRquest(context.Context, *HostInfoMessageRequest) (*HostInfoMessageResponse, error)
}

// UnimplementedGreetSeviceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetSeviceServer struct {
}

func (*UnimplementedGreetSeviceServer) DoHostInfoRquest(ctx context.Context, req *HostInfoMessageRequest) (*HostInfoMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoHostInfoRquest not implemented")
}

func RegisterGreetSeviceServer(s *grpc.Server, srv GreetSeviceServer) {
	s.RegisterService(&_GreetSevice_serviceDesc, srv)
}

func _GreetSevice_DoHostInfoRquest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostInfoMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetSeviceServer).DoHostInfoRquest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GreetSevice/DoHostInfoRquest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetSeviceServer).DoHostInfoRquest(ctx, req.(*HostInfoMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetSevice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GreetSevice",
	HandlerType: (*GreetSeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoHostInfoRquest",
			Handler:    _GreetSevice_DoHostInfoRquest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host.proto",
}
